app:
  container_name: reecewarrender_site
  build: ./
  volumes:
    - ./:/var/www
  ports:
    - 1337:1337
  environment:
    - NODE_ENV=development
    - PORT=1337
  command:
    sh -c 'npm i && npm run ${PLATFORM}'